### ISSUE TITLE
Beehave not working in Godot 4.2 mono

### ISSUE THREAD

**Issue by Shadowblitz16** [bitbrain/beehave#268]
Godot version: v4.2.stable.mono.official [46dc27791]

**Describe the bug**
errors on plugin enable
```
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger_tab.gd:-1 - Compile Error: 
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger.gd:-1 - Compile Error: 
  res://addons/beehave/plugin.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/plugin.gd" with error "Compilation failed". (User)
  res://addons/beehave/nodes/beehave_tree.gd:99 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/metrics/beehave_global_metrics.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/metrics/beehave_global_metrics.gd" with error "Parse error". (User)
Add Autoload
  res://addons/beehave/nodes/beehave_tree.gd:99 - Compile Error: Identifier not found: BeehaveGlobalDebugger
  res://addons/beehave/debug/global_debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/debug/global_debugger.gd" with error "Compilation failed". (User)
Add Autoload
  res://addons/beehave/debug/debugger_tab.gd:28 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
```

**To Reproduce**
1. Install betree from addons tab
2. enable plugin
3. see errors

**Expected behavior**
no errors

**Screenshots**
![image](https://github.com/bitbrain/beehave/assets/2453707/1f0524e2-2b1c-46fd-a057-ac46f9fc97ea)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser firefox?
 - Version 1.20.1
 

**Additional context**
why browser version?

**Comment by Megalukes** [comment]
I'm having the exact same issue. Same Godot version too.

**Comment by bitbrain** [comment]
Thanks for raising this.

**Comment by bitbrain** [comment]
@Megalukes can you try again with https://godotengine.org/asset-library/asset/1349?
