### PR TITLE
:bug: do not rely on autoloads to avoid startup errors

### LINKED ISSUE #202: Cannot create initial behaviour tree node
Godot version: 4.1
Beehave version 2.7.4

**Describe the bug**
Cannot create a beehave tree node. Editor throws an error in the output and nothing is changed in the scene.
Editor output:
```
Cannot get class ''.
editor/editor_data.cpp:581 - Parameter "p_object" is null.
editor/scene_tree_dock.cpp:2275 - Condition "!child" is true.
```

**To Reproduce**
1. Download and install beehave as instructed.
2. Create a new node anywhere (as a child, as a new scene) of type `BeehaveTree(beehave_tree.gd)`
3. Error thrown

**Expected behavior**

**Desktop:**
 - OS: Linux - Arch

**Additional context**

### LINKED ISSUE #268: Beehave not working in Godot 4.2 mono
Godot version: v4.2.stable.mono.official [46dc27791]

**Describe the bug**
errors on plugin enable
```
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger_tab.gd:-1 - Compile Error: 
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger.gd:-1 - Compile Error: 
  res://addons/beehave/plugin.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/plugin.gd" with error "Compilation failed". (User)
  res://addons/beehave/nodes/beehave_tree.gd:99 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/metrics/beehave_global_metrics.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/metrics/beehave_global_metrics.gd" with error "Parse error". (User)
Add Autoload
  res://addons/beehave/nodes/beehave_tree.gd:99 - Compile Error: Identifier not found: BeehaveGlobalDebugger
  res://addons/beehave/debug/global_debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/beehave/debug/global_debugger.gd" with error "Compilation failed". (User)
Add Autoload
  res://addons/beehave/debug/debugger_tab.gd:28 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
```

**To Reproduce**
1. Install betree from addons tab
2. enable plugin
3. see errors

**Expected behavior**
no errors

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser firefox?
 - Version 1.20.1
 

**Additional context**
why browser version?

### LINKED ISSUE #270: Addon errors on first load
Godot version: v4.2.1.stable.official [b09f793f5]

**Describe the bug**
Errors

**To Reproduce**
1. Open godot 4.2.1
2. Download beehave from asset browser
3. Enable it in project settings
4. 
```
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger_tab.gd:-1 - Compile Error: 
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/debug/debugger.gd" with error "Compilation failed". (User)
```

**Expected behavior**
No errors

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser: firefox
 - Version 121.0

**Additional context**
I recently tried updating from godot 4.2 mono to godot 4.2.1 non mono to try to get this plugin to work.

### LINKED ISSUE #282: Can't create beehave tree
Godot version: v4.2.1.stable.official [b09f793f5]

**Describe the bug**
I get errors when trying to create a new beehave tree.
No node is created

**To Reproduce**
1. Download Beehave
2. Enable it
3. Get Errors I already reported here https://github.com/bitbrain/beehave/issues/270
4. Try to create new BeehaveTree and scene root
5. Get this error ...
```
  Cannot get class ''.
  editor/editor_data.cpp:581 - Parameter "p_object" is null.
  editor/scene_tree_dock.cpp:2452 - Parameter "child" is null.
```
6. Clear logs
7. Create Node as scene root.
8. Add BeehaveTree as child.
9. Get this error ...
```
  Cannot get class ''.
  editor/editor_data.cpp:581 - Parameter "p_object" is null.
  editor/scene_tree_dock.cpp:2452 - Parameter "child" is null.
```

**Expected behavior**
It should work without errors

**Screenshots**
https://github.com/bitbrain/beehave/issues/270

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04, Linux kernal 6.2.0-39-generic (64 bit)
 - Browser: Firefox 121.0 (64-bit)
 - Version : Idk?

**Additional context**
I really want to use this plugin

### PR DESCRIPTION
**Pull request by bitbrain**
## Description

This pull request aims to solve some of the long standing issues with getting Beehave to work on first load.

## Addressed issues

- closes #282
- closes #270
- closes #268
- closes #202 

**Note: can please people test [this build of Beehave](https://github.com/bitbrain/beehave/tree/fix-startup-errors) to verify if this indeed fixes startup errors?**

### CODE REVIEW

File: addons/beehave/debug/debugger.gd [hunk 1]
```diff
@@ -2,6 +2,8 @@
 extends EditorDebuggerPlugin
 
 const DebuggerTab := preload("debugger_tab.gd")
+const BeehaveUtils := preload("res://addons/beehave/utils/utils.gd")
```
Comment (bitbrain) [inline addons/beehave/debug/debugger.gd:5]: This avoids issues at initial load in case the global class cache might not have initialized `BeehaveUtils` yet.

File: addons/beehave/debug/global_debugger.gd [hunk 2]
```diff
@@ -20,7 +20,7 @@ func _on_debug_message(message: String, data: Array) -> bool:
 
 
 func _set_active_tree(tree_id: int) -> void:
-	var tree: BeehaveTree = _registered_trees.get(tree_id, null)
+	var tree = _registered_trees.get(tree_id, null)
```
Comment (bitbrain) [inline addons/beehave/debug/global_debugger.gd:23]: Not ideal but removing `BeehaveTree` from here excludes this class from initial dependency lookups.

File: addons/beehave/nodes/beehave_tree.gd [hunk 3]
```diff
@@ -291,3 +291,15 @@ func _get_debugger_data(node: Node) -> Dictionary:
 
 func get_class_name() -> Array[StringName]:
 	return [&"BeehaveTree"]
+	
+
+# required to avoid lifecycle issues on initial load
+# due to loading order problems with autoloads
+func _get_global_metrics() -> Node:
```
Comment (bitbrain) [inline addons/beehave/nodes/beehave_tree.gd:298]: Autoloads will be added to the scene tree, so we can look them up dynamically. Unfortunately, referencing them directly may not work, as the global class cache may not have loaded them at the time this class here is parsed.
